import type { Metadata } from "next";
import "./globals.css";

import { cn } from "@/lib/utils";
import { SharedProviders } from "@/shared/shared-providers";
import type { Children } from "@/types/children";
import { GeistMono } from "geist/font/mono";
import { GeistSans } from "geist/font/sans";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<Children>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={cn(
          "antialiased min-h-screen font-sans",
          GeistSans.variable,
          GeistMono.variable,
        )}
      >
        <SharedProviders>{children}</SharedProviders>
      </body>
    </html>
  );
}
